Controllers/ProcessAttendanceController.cs
using EmpAttendance.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Globalization;
using System.Data.Entity;
using static EmpAttendance.GlobalVariable;

namespace EmpAttendance.Controllers
{
    public class ProcessAttendanceController : Controller
    {
        EmployeeAttendanceDBEntities db = new EmployeeAttendanceDBEntities();

        public ActionResult AttendanceReport()
        {
            ViewBag.TodayDate = GlobalFunction.GetDateTimeNow().ToString("MM/dd/yyyy");

            FillInOutDrp();
            return View();
        }
        [HttpPost]
        public ActionResult AttendanceSearch(DateTime FromDate, DateTime ToDate, int EmpId)
        {
            var lstAllDates = new List<DateTime>();
            string sql = "DELETE FROM Attendance WHERE AttendanceDate >= @p0 AND AttendanceDate <= @p1";

            if (EmpId != 0)
            {
                sql += " AND EmpId = @p2";
            }

            db.Database.ExecuteSqlCommand(sql, FromDate, ToDate, EmpId);

            for (var dt = FromDate; dt <= ToDate; dt = dt.AddDays(1))
            {
                lstAllDates.Add(dt);
            }

            List<int> distinctVal = db.Employee.Where(m => (m.Id == EmpId || EmpId == 0) && m.UserType == UserTypeEmployee).Select(x => x.Id).Distinct().OrderBy(x => x).ToList();

            foreach (var singleEmp in distinctVal)
            {
                CalculateAndRecordAttendance(singleEmp, lstAllDates);
            }

            List<Attendance> lstAttendance = GetAttlist(FromDate, ToDate, EmpId);
            return PartialView("_FilterAttendanceReport", lstAttendance);
        }
        private void CalculateAndRecordAttendance(int empId, List<DateTime> allDates)
        {
            try
            {
                int loopCount = 0;
                int weeklyTime = 0;
                List<DateTime> lstDate = new List<DateTime>();
                var empData = db.Employee.Where(m => m.Id == empId).FirstOrDefault();

                foreach (var item in allDates)
                {
                    TimeSpan workingTime = TimeSpan.Zero;
                    var holiday = db.tblMst_Holiday.Where(m => m.Day.Day == item.Day && m.Month == item.Month && m.Year == item.Year).FirstOrDefault();
                    List<InOutDetails> lstInOut = GetInOutDetailsForDate(empId, item);

                    if (holiday != null)
                    {
                        bool isSandwich = CheckForSandwichDay(empId, item);
                        var Approval = db.Approval.Where(m => m.ApprovalDate == item && m.EmpId == empId).FirstOrDefault();
                        if (Approval != null && Approval.IsApproved == true)
                        {
                            int Approvemin = 0;
                            Approvemin = (int)(Approval.ApprovedMinutes * Approval.ConvFactor);
                            UpdateOrInsertAttendanceAndApproveMin(empId, item, (int)PresentStatusId.Present, null, null, Approvemin);
                        }
                        else if (isSandwich)
                        {
                            UpdateAttendance(empId, item, (int)PresentStatusId.Sandwich, empData.DailyWorkingMin);
                        }
                        else
                        {
                            UpdateAttendance(empId, item, (int)PresentStatusId.Holiday, empData.DailyWorkingMin);
                        }
                    }
                    else if (lstInOut != null && lstInOut.Count > 0)
                    {
                        workingTime = TimeSpan.FromMinutes(CalculateWorkingMinutes(empId, item, lstInOut, empData));
                    }


                    if (workingTime != TimeSpan.Zero)
                    {
                        weeklyTime = weeklyTime + (int)workingTime.TotalMinutes;
                        lstDate.Add(item);
                    }

                    if (weeklyTime != 0 && ((item.DayOfWeek != DayOfWeek.Saturday &&
                        (allDates.Count - 1) == loopCount) || item.DayOfWeek == DayOfWeek.Saturday))
                    {
                        UpdateSettledMinutes(lstDate, empId, weeklyTime, empData.DailyWorkingMin);
                        if (item.DayOfWeek == DayOfWeek.Saturday)
                        {
                            weeklyTime = 0;
                            lstDate.Clear();
                        }
                    }
                    loopCount++;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An unexpected error occurred: {ex.Message}");
            }
        }
        public List<InOutDetails> GetInOutDetailsForDate(int empId, DateTime itemDate)
        {
            return db.InOutDetails
                .Where(r => DbFunctions.TruncateTime(r.PunchDateTime).Value == itemDate.Date && r.EmpId == empId)
                .ToList();
        }
        public int CalculateWorkingMinutes(int empId, DateTime item, List<InOutDetails> lstInout, Employee empData)
        {
            TimeSpan logInTime = TimeSpan.Zero;
            TimeSpan workingTime = TimeSpan.Zero;
            try
            {
                if (lstInout != null)
                {
                    foreach (var record in lstInout)
                    {
                        switch (record.InOutTypeId)
                        {
                            case (int)InOutTypeId.SuddenLeave:
                            case (int)InOutTypeId.Leave:
                                UpdateAttendance(empId, item, record.InOutTypeId, empData.DailyWorkingMin);
                                break;
                            case (int)InOutTypeId.In:
                                logInTime = record.PunchDateTime.TimeOfDay;
                                break;
                            case (int)InOutTypeId.Out:
                                workingTime = workingTime + (record.PunchDateTime.TimeOfDay - logInTime);
                                logInTime = TimeSpan.Zero;
                                break;
                            default:
                                break;
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An unexpected error occurred: {ex.Message}");
            }
            int workingTimeValue = Convert.ToInt32(workingTime.TotalMinutes);
            try
            {
                if (workingTime != TimeSpan.Zero)
                {
                    ProcessDailyAttendanceAndApproveMin(empId, item, empData.DailyWorkingMin,
                        Convert.ToInt32(empData.GapingMinutes), workingTimeValue, empData.DailyWorkingMin);
                }
                else if (logInTime != TimeSpan.Zero)
                {
                    UpdateAttendance(empId, item, (int)InOutTypeId.Leave, empData.DailyWorkingMin);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An unexpected error occurred: {ex.Message}");
            }
            return workingTimeValue;
        }
        public bool CheckForSandwichDay(int empId, DateTime item)
        {
            DateTime previousDate = item.AddDays(-1);
            var checkHolidayDate = db.tblMst_Holiday.Where(m => m.Day == previousDate).FirstOrDefault();
            var checkAttendanceDate = db.Attendance.Where(m => m.AttendanceDate == previousDate && m.EmpId == empId).FirstOrDefault();
            try
            {
                if (checkHolidayDate != null && checkAttendanceDate != null && checkAttendanceDate.PresentStatusId == (int)PresentStatusId.Sandwich)
                {
                    return true;
                }
                else if (checkAttendanceDate == null || checkAttendanceDate.PresentStatusId != (int)PresentStatusId.Present)
                {
                    TimeSpan workingTime = TimeSpan.Zero;
                    DateTime nextDate = item.AddDays(1);
                    checkHolidayDate = db.tblMst_Holiday.Where(m => m.Day == nextDate).FirstOrDefault();

                    while (checkHolidayDate != null)
                    {
                        nextDate = nextDate.AddDays(1);
                        checkHolidayDate = db.tblMst_Holiday.Where(m => m.Day == nextDate).FirstOrDefault();
                    }
                    List<InOutDetails> lstInOut = GetInOutDetailsForDate(empId, nextDate);
                    var empData = db.Employee.Where(m => m.Id == empId).FirstOrDefault();
                    if (lstInOut != null && lstInOut.Count > 0)
                    {
                        workingTime = TimeSpan.FromMinutes(CalculateWorkingMinutes(empId, nextDate, lstInOut, empData));
                    }

                    var checkInOutDate = db.InOutDetails.Where(m => m.PunchDateTime.Day == nextDate.Day && m.EmpId == empId).FirstOrDefault();
                    if (checkInOutDate == null || checkInOutDate.InOutTypeId == (int)PresentStatusId.Leave
                        || checkInOutDate.InOutTypeId == (int)PresentStatusId.SuddenLeave ||
                        workingTime == TimeSpan.Zero)
                    {
                        return true;
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"An unexpected error occurred: {ex.Message}");
            }
            return false;
        }
        private void ProcessDailyAttendanceAndApproveMin(int empId, DateTime attendanceDate, int dailyWorkingMin, int gapingMinutes, int totalMinutes, int calculatedMinutes)
        {
            int? approveMin = null;
            try
            {
                if (dailyWorkingMin > totalMinutes)
                {
                    var roundOfMinutes = dailyWorkingMin - (totalMinutes + RoundOffTime);

Views/ProcessAttendance/AttendanceReport.cshtml
@model IEnumerable<EmpAttendance.Models.Attendance>
@{
    ViewBag.Title = "AttendanceReport";
}


<div class="row mt-4">
    <div class="col-2">
        <label class="form-label mb-0">Employee</label>
        @Html.DropDownList("EmpId", null, "All", htmlAttributes: new { @ID = "EmpId", @Name = "EmpId", @class = "form-control form-select", @style = "width:100%" })
    </div>
    <div class="col-2">
        <label class="form-label mb-0">From Date</label>
        <input type="text" id="FromDate" name="FromDate" value="@ViewBag.TodayDate" class="form-control" readonly="readonly" />
    </div>
    <div class="col-2">
        <label class="form-label mb-0">To Date</label>
        <input type="text" id="ToDate" name="ToDate" value="@ViewBag.TodayDate" class="form-control" readonly="readonly" />
    </div>

    <div class="col-2">
        <input type="button" id="Search" class="btn btn-dark mt-4" value="Search" />
    </div>
</div>
<div>
    <table class="table table-bordered text-center table-striped mt-4" id="AttendanceList">
        <thead>
            <tr>
                <th>Employee Name</th>
                <th>Attendance Date</th>
                <th>Attendance Status</th>
                <th>Actual Time</th>
                <th>Calculated Time</th>
                <th>Setteled Time</th>
                <th>Holiday Time</th>
                <th>Sudden Leave Time</th>
                <th>Leave Time</th>
                <th>Overtime Time</th>
            </tr>
        </thead>
        <tbody>
            @Html.Partial("_FilterAttendanceReport", Model)
        </tbody>
    </table>
</div>
@section Scripts{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
    <script>

        $(document).ready(function () {
            $("#FromDate ").datepicker({
                changeMonth: true,
                changeYear: true,
            });
            $("#ToDate ").datepicker({
                changeMonth: true,
                changeYear: true,
            });


            $('#Search').click(function () {
                var fromdate = $('#FromDate').val();
                var todate = $('#ToDate').val();
                var EmployeeId = $('#EmpId').val() == "" ? 0 : $('#EmpId').val();
                var toDateObj = new Date(todate);
                var todayDate = new Date();
                if (toDateObj > todayDate) {
                    todate = moment(todayDate);
                }
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("AttendanceSearch", "ProcessAttendance")',
                        data: { FromDate: fromdate, ToDate: todate, EmpId: EmployeeId },
                        dataType: "html",
                        success: function (result) {
                        var table = $("table#AttendanceList > tbody.mytable");
                        $('#AttendanceList tbody').empty();
                        $("#AttendanceList TBODY TR").each(function () {
                            $(this).remove();
                        });
                        $('#AttendanceList tbody').append(result);
                        $.each(result, function (i, item) {
                        table.append(`<tr>
                        <td>${item.AttendanceDate}</td>
                        <td>${item.WorkingMin}</td>
                        <td>${item.EmpName}</td>
                        <td>${item.PresentStatus}</td>
                        <td>${item.CalculatedTime}</td>
                        <td>${item.SetteledMinutes}</td>
                        <td>${item.HolidayMinutes}</td>
                        <td>${item.SuddenLeaveMinutes}</td>
                        <td>${item.LeaveMinutes}</td>
                        <td>${item.OvertimeMinutes}</td>
                        </tr>`)});
                        }
                    });
            })
       })


    </script>
}

Views/ProcessAttendance/_FilterAttendanceReport.cshtml
@{
    Layout = null;
}
@model IEnumerable<EmpAttendance.Models.Attendance>
@if (Model != null)
{
    foreach (var item in Model)
    {
        <tr>
            <td>@item.EmpName</td>
            <td>@item.AttendanceDate.ToString("MM/dd/yyyy")</td>
            <td>@item.PresentStatus</td>
            <td>
                @(item.WorkingMin != null ? string.Format("{0} hrs {1} mins", item.WorkingMin / 60, item.WorkingMin % 60) : "")
            </td>
            <td>
                @(item.CalculatedMinutes != null ? string.Format("{0} hrs {1} mins", item.CalculatedMinutes / 60, item.CalculatedMinutes % 60) : "")
            </td>
            <td>
                @(item.SetteledMinutes != null ? string.Format("{0} hrs {1} mins", item.SetteledMinutes / 60, item.SetteledMinutes % 60) : "")
            </td>
            <td>
                @(item.HolidayMinutes != null ? string.Format("{0} hrs {1} mins", item.HolidayMinutes / 60, item.HolidayMinutes % 60) : "")
            </td>
            <td>
                @(item.SuddenLeaveMinutes != null ? string.Format("{0} hrs {1} mins", item.SuddenLeaveMinutes / 60, item.SuddenLeaveMinutes % 60) : "")
            </td>
            <td>
                @(item.LeaveMinutes != null ? string.Format("{0} hrs {1} mins", item.LeaveMinutes / 60, item.LeaveMinutes % 60) : "")
            </td>
            <td>
                @(item.OvertimeMinutes != null ? string.Format("{0} hrs {1} mins", item.OvertimeMinutes / 60, item.OvertimeMinutes % 60) : "")
            </td>
        </tr>
    }
}
else
{
    <tr>
        <td colspan="6">
        </td>
    </tr>
}
@functions {
    string ConvertMinutesToHoursAndMinutes(int totalMinutes)
    {
        int hours = totalMinutes / 60;
        int remainingMinutes = totalMinutes % 60;

        return $"{hours} hours and {remainingMinutes} minutes";
    }
}