Models/Approval.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpAttendance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public int Id { get; set; }
        public int EmpId { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public int WorkingMinutes { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public bool IsApproved { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ApprovedMinutes { get; set; }
        public Nullable<decimal> ConvFactor { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}

Controllers/ApprovalController.cs
using EmpAttendance.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmpAttendance.Controllers
{
    [AuthorizationFilter]
    public class ApprovalController : Controller
    {
        EmployeeAttendanceDBEntities db = new EmployeeAttendanceDBEntities();
        // GET: Approval
        public ActionResult Create()
        {
            var model = new Approval();
            model.ApprovalDate = GlobalFunction.GetDateTimeNow();
            FillEmployee(model);
            return View(model);
        }

        [HttpPost]
        public ActionResult Create(Approval mdl)
        {
            if (mdl.IsApproved == true)
            {
                mdl.ApprovedTime = Convert.ToDateTime(GlobalFunction.GetDateTimeNow().ToString("yyyy-MM-dd HH:mm ")); 
            }
            else
            {
                mdl.ApprovedTime = null;
            }
            mdl.CreatedTime = Convert.ToDateTime(GlobalFunction.GetDateTimeNow().ToString("HH:mm:ss "));
            mdl.ApprovedById = GlobalVariable.UserId;

            if (mdl.Id > 0)
            {
                Approval objExsisting = db.Approval.Find(mdl.Id);
                objExsisting.Id = mdl.Id;
                objExsisting.EmpId = mdl.EmpId;
                objExsisting.ApprovalDate = mdl.ApprovalDate;
                objExsisting.WorkingMinutes = mdl.WorkingMinutes;
                objExsisting.ApprovedById = GlobalVariable.UserId;
              
                if(GlobalVariable.IsAdmin == true)
                {
                    objExsisting.ApprovedTime = mdl.ApprovedTime;
                    objExsisting.IsApproved = mdl.IsApproved;
                }
                objExsisting.Remark = mdl.Remark;

                db.Entry(objExsisting).State = EntityState.Modified;
            }
            else
            {
                var data = db.Approval.Where(n => n.ApprovalDate == mdl.ApprovalDate && n.EmpId == mdl.EmpId).FirstOrDefault();
                if (data == null)
                {
                    db.Approval.Add(mdl);
                }
                else
                {
                    return Json("Approval For The Selected Date Already Exist");
                }
            }
            db.SaveChanges();
            return Json("success");
        }

        public ActionResult ApprovalList()
        {
            ViewBag.TodayDate = GlobalFunction.GetDateTimeNow();

            var model = new Approval();
            FillEmployee(model);
            List<Approval> lst = GetApprovallist(null ,null ,GlobalVariable.UserId);
           
            return View(lst);
        }

        [HttpPost]
        public PartialViewResult _ApprovalList(string FromDate, string ToDate, int EId)
        {
            List<Approval> lst = GetApprovallist(FromDate, ToDate, EId);
            return PartialView("_ApprovalList", lst);
        }

        private List<Approval> GetApprovallist(string FromDate, string ToDate, int EId)
        {
            var ApprovalData = from qd in db.Approval
                               join E in db.Employee on qd.EmpId equals E.Id
                               orderby qd.ApprovalDate descending
                               select new
                               {
                                   qd.Id,
                                   qd.EmpId,
                                   qd.WorkingMinutes,
                                   qd.ApprovalDate,
                                   qd.CreatedTime,
                                   qd.ApprovedTime,
                                   qd.IsApproved,
                                   E.EmployeeCode,
                                   E.Name
                               };

            if(EId != 0 && (string.IsNullOrEmpty(FromDate) || string.IsNullOrEmpty(ToDate)))
            {
                if (GlobalVariable.IsAdmin == false)
                {
                    ApprovalData = ApprovalData.Where(x => x.EmpId == EId);
                }
            }
            else
            {
                DateTime fromdate = DateTime.ParseExact(FromDate, "MM/dd/yyyy", CultureInfo.InvariantCulture);
                DateTime todate = DateTime.ParseExact(ToDate, "MM/dd/yyyy", CultureInfo.InvariantCulture);

                if (EId != 0)
                {
                    ApprovalData = ApprovalData.Where(x => x.EmpId == EId && x.ApprovalDate.Day >= fromdate.Day && x.ApprovalDate.Month >= fromdate.Month && x.ApprovalDate.Year >= fromdate.Year &&
                               x.ApprovalDate.Day <= todate.Day && x.ApprovalDate.Month <= todate.Month && x.ApprovalDate.Year <= todate.Year);
                }
                else
                {
                    ApprovalData = ApprovalData.Where(x => x.ApprovalDate.Day >= fromdate.Day && x.ApprovalDate.Month >= fromdate.Month && x.ApprovalDate.Year >= fromdate.Year &&
                              x.ApprovalDate.Day <= todate.Day && x.ApprovalDate.Month <= todate.Month && x.ApprovalDate.Year <= todate.Year);
                }
            }

            List<Approval> lst = new List<Approval>();

            if (ApprovalData != null)
            {
                foreach (var item in ApprovalData)
                {
                    Approval modelQC = new Approval();
                    modelQC.Id = item.Id;
                    modelQC.EmpId = item.EmpId;
                    modelQC.WorkingMinutes = item.WorkingMinutes;
                    modelQC.ApprovalDate = item.ApprovalDate;
                    modelQC.ApprovedTime = item.ApprovedTime;
                    modelQC.CreatedTime = item.CreatedTime;
                    modelQC.IsApproved = item.IsApproved;
                    modelQC.EmpCode = item.EmployeeCode;
                    modelQC.EmpName = item.Name;
                    lst.Add(modelQC);
                }
            }

            return lst;
        }

        public ActionResult Edit(int id)
        {
            var data = db.Approval.Where(n => n.Id == id).FirstOrDefault();
            if(GlobalVariable.IsAdmin == false)
            {
                if(data.IsApproved == true)
                {
                    return RedirectToAction("ApprovalList");
                }
            }

           // software pvt. ltd ecom

            FillEmployee(data);
            var worktime = data.WorkingMinutes;
            if (data.WorkingMinutes < 0)
            {
                data.Time = true;
            }
            data.WorkingMinutes = Math.Abs(worktime);
            return View("Create", data);
        }

        public ActionResult Delete(int id)
        {
            var data = db.Approval.Find(id);
            db.Approval.Remove(data);
            db.SaveChanges();
            return RedirectToAction("ApprovalList");
        }

        private void FillEmployee(Approval model)
        {
            List<SelectListItem> drpEmp = db.Employee.OrderBy(m => m.Name).Select(m => new SelectListItem
            {
                Value = m.Id.ToString(),
                Text = m.Name,
            }).ToList();

            if (model != null && model.EmpId > 0)
            {
                ViewBag.EmpId = new SelectList(drpEmp, "Value", "Text", model.EmpId.ToString());
            }
            else
            {
                if (GlobalVariable.IsAdmin == false)
                {
                    ViewBag.EmpId = new SelectList(drpEmp, "Value", "Text", GlobalVariable.UserId.ToString());
                }
                else
                {
                    ViewBag.EmpId = new SelectList(drpEmp, "Value", "Text");
                }
            }
        }
    }
}

Views/Approval/ApprovalList.cshtml
@model IEnumerable<EmpAttendance.Models.Approval>
@{
    ViewBag.Title = "ApprovalList";
}

<h2>Approval List</h2>
<style>

    span.error {
        display: block;
        visibility: hidden;
        color: red;
        font-size: 90%;
    }

    .posspan {
        position: relative;
        top: -20px;
    }
</style>
<table class="table text-center" id="ApprovalList">
    <div class="row">
        <div class="col-2">
            <label class="form-label mb-0">Employee</label>
            @if (GlobalVariable.IsAdmin == false)
            {
                @Html.DropDownList("EmpId", null, htmlAttributes: new { @ID = "EmpId", @Name = "EmpId", @class = "form-control form-select ", @style = "width:100%", @disabled = "disabled" })
            }
            else
            {
                @Html.DropDownList("EmpId", null, "All", htmlAttributes: new { @ID = "EmpId", @Name = "EmpId", @class = "form-control form-select ", @style = "width:100%" })
            }
        </div>
        <div class="col-2">
            <label class="form-label mb-0">From Date</label>
            <input type="text" id="FromDate" name="FromDate" value="@string.Format("{0:dd/MM/yyyy}" ,  @ViewBag.TodayDate)" class="form-control" readonly="readonly" />
        </div>
        <div class="col-2">
            <label class="form-label mb-0">To Date</label>
            <input type="text" id="ToDate" name="ToDate" value="@string.Format("{0:dd/MM/yyyy}" ,  @ViewBag.TodayDate)" class="form-control" readonly="readonly" />
        </div>
        <div class="col-2">
            <input type="button" id="Search" class="btn btn-dark mt-4" value="Search" />
        </div>
        <div class="col-4">
            <div class="float-end mt-4">
                @Html.ActionLink("Create", "Create", "", new { @class = "btn btn-info " })
            </div>
        </div>
    </div>
    <thead>
        <tr>
            <th>Employee Code</th>
            <th>Employee Name</th>
            <th>Approval Date</th>
            <th>Working Time</th>
            <th>Created Time</th>
            <th>Approved Time</th>
            <th>Approved</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @Html.Partial("_ApprovalList", Model)
    </tbody>
</table>
@section Scripts{
    @*<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
    <link href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css" />

    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>*@

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
    <script>
    $(document).ready(function () {
        $("#FromDate ").datepicker({
            dateFormat: 'dd/mm/yy'
        });
        $("#ToDate ").datepicker({
            dateFormat: 'dd/mm/yy'
        });
        $('#Search').click(function () {
                var fromdate = $('#FromDate').val();
                var todate = $('#ToDate').val();
                var formattedtoDate = moment(todate, 'DD/MM/YYYY').format('MM/DD/YYYY');
                var formattedfromDate = moment(fromdate, 'DD/MM/YYYY').format('MM/DD/YYYY');
                var EmployeeId = $('#EmpId').val() == "" ? 0 : $('#EmpId').val();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("_ApprovalList", "Approval")',
                    data: { FromDate: formattedfromDate, ToDate: formattedtoDate, EId: EmployeeId },
                    dataType: "html",
                    success: function (result) {
                        var table = $("table#ApprovalList > tbody.mytable");
                        $('#ApprovalList tbody').empty();
                        $("#ApprovalList TBODY TR").each(function () {
                            $(this).remove();
                        });
                        $('#ApprovalList tbody').append(result);
                        $.each(result, function (i, item) {
                            table.append(`<tr>
                               <td>${item.EmpCode}</td>
                               <td>${item.EmpName}</td>
                               <td>${item.ApprovalDate.ToString("dd/MM/yyyy")}</td>
                               <td>${string.Format("{0} hrs {1} mins", item.WorkingMinutes / 60, item.WorkingMinutes % 60)}</td>
                               <td>${item.CreatedTime.ToString("dd/MM/yyyy hh:mm tt")}</td>
                               <td>${item.ApprovedTime.ToString("dd/MM/yyyy hh:mm tt") }</td>
                             </tr>`)
                        });
                    },
                    error: function (error) {
                        console.log("error");
                    }
             });
        })
    })

    </script>
}

Views/Approval/Create.cshtml
@model EmpAttendance.Models.Approval

<style>
    .gradient-custom {
        background: rgb(140,133,255);
        background: linear-gradient(90deg, rgba(140,133,255,1) 0%, rgba(0,121,238,1) 44%, rgba(0,212,255,1) 100%);
        padding: 10px
    }

    .card-custom {
        border-bottom-left-radius: 10% 50%;
        border-top-left-radius: 10% 50%;
        background-color: #f8f9fa;
    }

    .input-custom {
        background-color: white;
    }

    .white-text {
        color: hsl(52, 0%, 98%);
        font-weight: 100;
        font-size: 14px;
    }

    .back-button {
        background-color: hsl(52, 0%, 98%);
        font-weight: 700;
        color: black;
        margin-top: 50px;
    }

    .posdiv {
        position: relative;
        top: -20px
    }

    span.error {
        display: block;
        visibility: hidden;
        color: red;
        font-size: 90%;
    }

    .Checkboxsize {
        margin-top: 5px;
        width: 25px;
        height: 25px
    }

    .hrmsg {
        position: relative;
        top: -20px
    }

    .bottomdiv {
        position: relative;
        top: -70px;
    }

    .cardbodymargin {
        margin-left: 105px
    }

    .bottomdivs {
        position: relative;
        top: -100px;
    }

    h4 {
        padding-right: 100px;
    }

    label {
        font-weight: bold;
    }
</style>

<div class="row mt-3 mx-3 gradient-custom" style="margin-top:25px ; height:600px ; width:100%">
    <div class="col-md-3">
        <div style="margin-top: 50px; margin-left: 10px;" class="text-center">
            <i id="animationDemo" data-mdb-animation="slide-right" data-mdb-toggle="animation"
               data-mdb-animation-reset="true" data-mdb-animation-start="onScroll"
               data-mdb-animation-on-scroll="repeat" class="fas fa-3x fa-shipping-fast text-white"></i>
            <h3 class="mt-3 text-white">Welcome</h3>
            <p class="white-text">Enter Your Right ✔ Detail...</p>
            @Html.ActionLink("List", "ApprovalList", "", new { @class = "btn btn-dark" })
        </div>
    </div>
    <div class="col-md-9 justify-content-center">
        <div class="card card-custom pb-4 style=" height:600px"">
            <div class="card-body mt-0 cardbodymargin" style="height:550px">
                <div class="text-center mb-3 pb-2 mt-3">
                    <h4 class="mainhead" style="color: #495057 ;"> Attendance Approval</h4>
                    @*<hr style="width:250px; margin:0px 150px" />*@
                </div>
                @using (Html.BeginForm("Create", "Approval", FormMethod.Post))
                {
                    <input type="hidden" id="Id" class="form-control input-custom" value="@Model.Id" name="Id" />
                    <input type="hidden" id="CreatedById" class="form-control input-custom" value="@Model.CreatedById" name="CreatedById" />
                    <div class="row mb-4 ">
                        <div class="col">
                            <div class="form-outline">
                                <label class="form-label mb-0">Employee</label>
                                @if (Model.Id > 0 || GlobalVariable.IsAdmin == false)
                                {
                                    @Html.DropDownList("EmpId", null, "Select", htmlAttributes: new { @ID = "EmpId", @Name = "EmpId", @class = "form-control form-select ", @style = "width:100%", @disabled = "disabled" })
                                }
                                else
                                {
                                    @Html.DropDownList("EmpId", null, "Select", htmlAttributes: new { @ID = "EmpId", @Name = "EmpId", @class = "form-control form-select ", @style = "width:100%" })
                                }
                                <span class="error">Please select employee</span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-outline">
                                <label class="form-label mb-0">Approval Date</label>
                                <input type="text" id="ApprovalDate" name="ApprovalDate" class="form-control" value="@string.Format("{0:dd-MM-yyyy}" , Model.ApprovalDate)" readonly="readonly" />
                                <span class="error">Approval date required</span>
                            </div>
                        </div>

                    </div>
                    <div class="row mb-4 posdiv">
                        <div class="col">
                            <div class="form-outline">
                                <label class="form-label mb-0">Hours</label>
                                <input type="number" id="TotalHours" class="form-control input-custom" maxlength="1" value="@string.Format("{0}" , Model.WorkingMinutes / 60)" onkeydown="if(event.key==='.'){event.preventDefault();}" oninput="event.target.value = event.target.value.replace(/[^0-9]*/g,'');" name="TotalHours" />
                                <span class="error"> Time Must Be Greater Than Zero!</span>
                                <span class="error hrmsg"> Time can not be greater than 8 hours</span>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-outline">
                                <label class="form-label mb-0">Minutes</label>
                                <input type="number" id="TotalMinutes" class="form-control input-custom" maxlength="2" value="@string.Format("{0}" , Model.WorkingMinutes % 60)" onkeydown="if(event.key==='.'){event.preventDefault();}" oninput="event.target.value = event.target.value.replace(/[^0-9]*/g,'');" name="TotalMinutes" />
                                <span class="error minmsg"> Minutes can not be greater than 59 minutes</span>
                            </div>
                        </div>
                    </div>
                    <div class="row d-flex mb-5 bottomdiv">
                        <div class="col mt-3">
                            <input type="radio" id="Time1" name="Time" value="+" checked>
                            <label>Over-Time</label><br>
                            <input type="radio" id="Time2" name="Time" value="-" @( Model.Time == true ? "checked" : "" )>
                            <label>Under-Time</label><br>
                            <span class="error">Over time / Under time required</span>
                        </div>
                        @if (GlobalVariable.IsAdmin == true)
                        {
                            <div class="col mt-3">
                                <label class="form-label mb-0">Is Approved</label>
                                <input type="checkbox" value="true" @( Model.IsApproved == true ? "checked" : "" ) name="IsApproved" id="IsApproved" class="btn btn-dark  " />
                            </div>
                        }
                    </div>
                    <div class="row d-flex mb-5 bottomdivs">
                        <div class="col">
                            <div class="form-outline">
                                <label class="form-label mb-0">Remark</label>
                                <textarea id="Remark" name="Remark" class="form-control input-custom">@Model.Remark</textarea>
                            </div>
                        </div>
                        <div class="error text-danger" id="allerrormsg"> </div>
                        <div class="col">
                            <div class="float-end  mt-5">
                                <button type="button" class="btn btn-primary btn-rounded mx-5"
                                        style="background-color: #0062CC ;" id="Checkbtn">
                                    Save
                                </button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.js"></script>
    <script>
    $(document).ready(function () {

      $("#ApprovalDate").datepicker({
        dateFormat: 'dd-mm-yy'
      });

        $("#Checkbtn").click(function () {
            var minutes = $('#TotalMinutes').val();
            var hours = $('#TotalHours').val();
            var CheckMinutes =  ((Number(hours) * 60) + Number(minutes));
            var isAllValid = true;
            if ($('#TotalHours').val().trim() == '' || $('#TotalHours').val().trim() == 0) {
                if ($('#TotalMinutes').val().trim() == '' || $('#TotalMinutes').val().trim() == 0) {
                    $('#TotalHours').siblings('span.error').css('visibility', 'visible');
                    isAllValid = false;
                }
                else {
                    isAllValid = true;
                }
            }
            else {
                $('#TotalHours').siblings('span.error').css('visibility', 'hidden');
            }
            if ($('#TotalHours').val().trim() > 8 || CheckMinutes > 480)  {
                $('#TotalHours').siblings('span.error').css('visibility', 'hidden');
                $('#TotalHours').siblings('span.hrmsg').css('visibility', 'visible');
                isAllValid = false;
            }
            else {
                $('#TotalHours').siblings('span.hrmsg').css('visibility', 'hidden');
            }
            if ($('#TotalMinutes').val().trim() > 59) {
                if ($('#TotalHours').val().trim() > 8) {
                    $('#TotalHours').siblings('span.hrmsg').css('visibility', 'visible');
                }
                else {
                    $('#TotalHours').siblings('span.error').css('visibility', 'hidden');
                    $('#TotalMinutes').siblings('span.minmsg').css('visibility', 'visible');
                    isAllValid = false;
                }
            }
            else {
                $('#TotalMinutes').siblings('span.minmsg').css('visibility', 'hidden');
            }
            if ($('#EmpId').val().trim() == '') {
                $('#EmpId').siblings('span.error').css('visibility', 'visible');
                isAllValid = false;
            }
            else {
                $('#EmpId').siblings('span.error').css('visibility', 'hidden');
            }
            if ($('#ApprovalDate').val().trim() == '') {
                $('#ApprovalDate').siblings('span.error').css('visibility', 'visible');
                isAllValid = false;
            }
            else {
                $('#ApprovalDate').siblings('span.error').css('visibility', 'hidden');
            }

            var checkedRadio = $('input[type="radio"]:checked');
            if (checkedRadio.length > 0) {
                $('#Time1').siblings('span.error').css('visibility', 'hidden');
            }
            else {
                $('#Time1').siblings('span.error').css('visibility', 'visible');
                isAllValid = false;
            }

            if (isAllValid) {
                var chekval = false;
                var checkedValue = $('#IsApproved:checked').val();
                if (checkedValue != null) {
                    chekval = true;
                }
                var TimeSign = null;
                TimeSign=  $('input[type="radio"]:checked').val()
                var minutes = $('#TotalMinutes').val();
                var hours = $('#TotalHours').val();
                var TotalMinutes = TimeSign + ((Number(hours) * 60) + Number(minutes));
                var startDate = $('#ApprovalDate').val();
                var formattedDate = moment(startDate, 'DD-MM-YYYY').format('MM-DD-YYYY');

                var data = {
                Id: $('#Id').val().trim(),
                Remark: $('#Remark').val().trim(),
                EmpId: $('#EmpId').val().trim(),
                ApprovalDate: formattedDate,
                IsApproved: chekval,
                CreatedById: $('#EmpId').val().trim(),
                WorkingMinutes: TotalMinutes,
                }

              $.ajax({
                 type: "POST",
                 url: '@Url.Action("Create", "Approval")',
                 data: { mdl: data },
                 dataType: "json",
                  success: function (result) {
                      if (result == "success") {
                          document.location.href = '/Approval/ApprovalList'
                      }
                      else {
                          $('#allerrormsg').text(result)
                      }
                  }
              });
            }
       })
    });

    </script>
}

Views/Approval/_ApprovalList.cshtml
@{
    Layout = null;
}

@if (Model != null)
{
    foreach (var item in Model)
    {
        <tr class="@item.Id">
            <td>@item.EmpCode</td>
            <td>@item.EmpName</td>
            <td>@item.ApprovalDate.ToString("dd/MM/yyyy")</td>
            <td>@string.Format("{0} hrs {1} mins", item.WorkingMinutes / 60, Math.Abs(item.WorkingMinutes % 60))</td>
            <td>@item.CreatedTime.ToString("dd/MM/yyyy hh:mm tt")</td>
            <td>@(item.ApprovedTime == null ? "" : item.ApprovedTime.ToString("dd/MM/yyyy hh:mm tt") )</td>
            <td>
                <input type="checkbox" value="true" @(item.IsApproved == true ? "checked" : "" ) onclick="return false;" onkeydown="return false;" />
            </td>
            <td>
                @if (item.IsApproved == false || GlobalVariable.IsAdmin == true)
                {
                    @Html.ActionLink("Edit", "Edit", new { @id = item.Id }, new { @class = "btn btn-info" })
                }
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { @id = item.Id }, new { onclick = "return confirm('Are you sure you want to delete this record? ')", @class = " btn btn-danger btncreate " })
            </td>
        </tr>
    }
}
else
{
    <tr>
        <td colspan="6">
            <h3>No data available</h3>
        </td>
    </tr>
}